### PR TITLE
Fix parsing X-Forwarded-For header.

### LINKED ISSUE #285: Get real client IP address behind the reverse proxy
I'm using the nginx server as a reverse proxy for Qt TreeFrog as described on this page:

https://www.treefrogframework.org/en/user-guide/cooperation-with-the-reverse-proxy-server/

The problem is that in this case the `TActionController::clientAddress()` and `TWebSocketEndpoint::peerAddress()` functions return the proxy address instead of the client's IP address.

In nginx, you can add an X-Forwarded-For header containing the client's IP address:

`proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`

but unfortunately Qt TreeFrog does not have functionality similar to that of mod_remoteip Apache server:

https://httpd.apache.org/docs/current/es/mod/mod_remoteip.html

Would it be possible to add an option in the TreeFrog configuration to define the name of the HTTP header containing the client's original IP address (RemoteIPHeader) and the list of trusted proxy (RemoteIPTrustedProxy) ? The `TActionController::clientAddress()` function would return the client's IP address instead of the proxy IP address if the proxy is trusted.

Thanks.

### PR DESCRIPTION
**Pull request by amiart**
Fixes parsing of the header, and it is now possible to trust Unix domain socket proxy and proxy servers in a subnet.

In nginx configuration (reverse proxy) add this line:
```
proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;
```

In Treefrog configuration add these lines:
```
EnableForwardedForHeader=true
ParseForwardedForHeaderRecursively=false
TrustedProxyServers="unix:; 192.168.0.10; 192.168.0.20"   # the value must be in quotes
```

Fixes #285

### CODE REVIEW

**Comment by treefrogframework** [comment]
To keep the specification simple, I would like to omit the ParseForwardedForHeaderRecursively parameter. 
And I don't think that parsing "unix:" is necessary. No one writes the string "unix:" in the "X-Forwarded-For" header, right?

**Comment by amiart** [comment]
> To keep the specification simple, I would like to omit the ParseForwardedForHeaderRecursively parameter.

The ParseForwardedForHeaderRecursively parameter is needed, if you want to trust only proxies that connect directly to the treefrog server, e.g. when I'm in a local network I connect through a proxy server 192.168.1.10, and being outside this network I connect through a proxy server with a public IP like 213.25.134.23 and then I don't want to trust 192.168.1.10 anymore.

This is an equivalent to the **real_ip_recursive** parameter of the nginx server:
https://nginx.org/en/docs/http/ngx_http_realip_module.html

If you don't like the name of this parameter then you can change it.

> And I don't think that parsing "unix:" is necessary. No one writes the string "unix:" in the "X-Forwarded-For" header, right?

The implementation doesn't expect 'unix:' in the header - see the code.
Setting TrustedProxyServers='unix:' is required if we have a treefrog server listening on Unix domain socket and nginx as a reverse proxy as described on this page:
https://www.treefrogframework.org/en/user-guide/cooperation-with-the-reverse-proxy-server/

See also nginx **set_real_ip_from** parameter - it accepts 'unix:' value:
https://nginx.org/en/docs/http/ngx_http_realip_module.html

**Comment by amiart** [comment]
Fix for #285

**Comment by treefrogframework** [comment]
> See also nginx set_real_ip_from parameter - it accepts 'unix:' value:
> https://nginx.org/en/docs/http/ngx_http_realip_module.html

About the node identifier, does it meet the RFC7239?
It seems the spec for nginx only.

**Comment by amiart** [comment]
The apache server doesn't have it, so it seems it's a nginx-specific solution.

**Comment by treefrogframework** [comment]
I think it can support the following two patterns:
  Example 2: "192.168.1.10, 192.168.1.20"
  Example 3: "10.0.1.0/24, 10.0.2.0/255.255.255.0"

**Comment by amiart** [comment]
So you want to always trust proxy for unix: socket ?

**Comment by amiart** [comment]
Changed the code, so now TrustedProxyServers parameter accepts only IP addresses or subnets and the UNIX domain socket proxy is always trusted.

**Comment by treefrogframework** [comment]
About unix domain, it's a specification in RFC?
I don't desire to implement specifications that are not in RFC.

**Comment by amiart** [comment]
Sorry, but I don't have such knowledge.
But since the treefrog allow to listen on UNIX domain socket and recommends 
using a proxy server for HTTPS or compression, it should be possible to trust such a proxy.

**Comment by treefrogframework** [comment]
Unfortunately, this pull-request is not acceptable.
I appreciate your understanding.

**Comment by amiart** [comment]
What's wrong with the patch ?
The unix domain socket check is only for clientAddress() (the host that connects directly to treefrog).
It doesn't expect unix: in X-Forwarded-For header and TrustedProxyServers parameter, so the RFC is not violated.

**Pull request closed without merging**
