### PR TITLE
Performance improvements

### PR DESCRIPTION
**Pull request by amiart**

### CODE REVIEW

**Comment by treefrogframework** [comment]
Thanks.

**Comment by amiart** [comment]
Hi, what is the reason that the TSessionFileStore change has been rejected ? I thought it was ok.

**Comment by treefrogframework** [comment]
I didn't understand what changed. No your comments.
I think that enough test is needed about file session store. See #146.

**Comment by amiart** [comment]
When a wrote this change I was aware of  #146. The change doesn't break anything.
Here is what was changed:
- when running only app server we don't have to lock processes, because there is only one tadpole process, the lock for threads is enough in this situation.
- the long-running operations (session compression and serialization) is done before locking threads and processes. The locks are neccessary only when we write to a file. Similarly in find() we release all lock just after read the file, so we can do the decompression without blocking other requests.
- rwLock doesn't have to be Recursive, because there is no recursion in store() and find() methods.
- added some more error checks (file write error etc.)

**Comment by amiart** [comment]
Hi, do you still consider the possibility of applying this change in the TSessionFileStore class, or do you prefer to stay with the current implementation? In the latter case, I will apply this change to my local copy of the Treefrog framework.

**Comment by amiart** [comment]
I applied this change in my local copy of treefrog.
So far it works without problems.

**Pull request merged**
