### PR TITLE
Minor performance improvements for HTTP requests

### PR DESCRIPTION
**Pull request by amiart**
I also noticed that the request header is parsed twice, first in the THttpSocket::readRequest() function and then in THttpRequest::generate(). Improving this would speed up the handling of requests a bit, but it would require more changes, and I didn't want to break anything.

### CODE REVIEW

**Comment by treefrogframework** [comment]
How fast has the patch improved?
You've changed some logic, so I worry it's not all tested.

**Comment by amiart** [comment]
About 1,5%  - that's why I called it minor performance improvement.
The measurement was done using siege and callgrid:

siege -b -c 10 -t 60S http://localhost:8800/auth/login

QObject::connect() before:
QObject_connect_before

QObject::connect() after:
QObject_connect_after


getUTCTimeString() before:
getUTCTimeString_before

getUTCTimeString() after:
getUTCTimeString_after

All changes tested and works.

Before the changes in the siege test, I obtained the result of 1038 transactions.
After applying all changes I submited and increasing the Session.GcProbability parameter from 100 to 1000, I obtained 1274 transactions in 60 seconds under Qt 5.9.7. 
For Qt 5.12+ and later the difference will be smaller.

The controller function that was tested uses getAll() and render().

**Comment by treefrogframework** [comment]
Partially merged. 3d5baff6f0d52c11e7e83b218269697f89af3023

**Comment by amiart** [comment]
Gosh, undoing the change #304 (TSqlObject::syncToObject () and TSqlObject::syncToSqlRecord())  you actually reduced performance gain to 0.5%. I also don't understand why ORM parameters cannot be const. Can you explain why you made that decision?

**Comment by treefrogframework** [comment]
Thanks.
Commited in 691c6b9edbfdeeeb1e0c9f05e1246bc74f09668f.

**Pull request closed without merging**
