### PR TITLE
All Chinese user guide docs be verified.

### PR DESCRIPTION
**Pull request by hks2002**
1. All files saved with UTF-8.
2. Reviewed docs content.
3. Redo composition.

### CODE REVIEW

**Comment by treefrogframework** [comment]
Cannot merge the pull-request.
You can update current master branch.
Try again please.

**Comment by hks2002** [comment]
Sorry, I don't known how to do it now.
Does it caused by different files formats(UCS-16 and UTF8)?

**Comment by treefrogframework** [comment]
You should resolve the conflicts.

**Comment by hks2002** [comment]
Should I pull a request delete  them first? I can't see the  conflicts, these files have been saved as from UCS-16 into UTF8, I don't known how to do now.

**Comment by hks2002** [comment]
Fixed.

**Comment by treefrogframework** [comment]
<span style="color: #b22222">...</span>
  ↓
##### ....
is correct. Could you revert them ?

If possible, would you trim trailing white spaces?

**Comment by hks2002** [comment]
Do you say the object-document-mapping-on-mongodb.md? 
Yes, it is a mistake.

**Comment by treefrogframework** [comment]
see https://github.com/treefrogframework/treefrog-framework/pull/151/files

**Comment by hks2002** [comment]
I haven't notes that you have changed all \<span style="color: #b2222"\>\</span\> to #### these two days. I thought it is my mistake made in some files.
Now all \<span style="color: #b2222"\>\</span\> have been changed to ####,  just as you do.

**Comment by treefrogframework** [comment]
jekyll error occurred.

Error reading file /home/aoyama/treefrog-framework/docs/user-guide/ch/introduction/license.md: (<unknown>): mapping values are not allowed in this context at line 3 column 8 
Error reading file /home/aoyama/treefrog-framework/docs/user-guide/ch/introduction/requirements.md: (<unknown>): mapping values are not allowed in this context at line 3 column 8 

see https://github.com/treefrogframework/treefrog-framework/tree/master/docs

**Comment by hks2002** [comment]
Fixed, missing a blank space after the title:

**Comment by treefrogframework** [comment]
If sending a pull request, you should send from another branch, not master branch.
It is hard to review patches from master.

**Pull request merged**
