### PR TITLE
Changed some quotes/Corrected some words in English documents

### PR DESCRIPTION
**Pull request by hks2002**
’ ---> '
‘ ---> '
” ---> "
“ ---> "
\<br\>. ---> .\<br\>
MondoDB ---> MongoDB
your are ---> you are
sser suthenticiation ---> user authenticiation
Otoma ---> Otama
instal ---> install
provess ---> process
application route ---> application root
entpoint ---> endpoint
testlog.cpp ---> testBlog.cpp

### CODE REVIEW

**Comment by treefrogframework** [comment]
Thank you very much!
Great!

**Comment by hks2002** [comment]
I translated user guide to Chinese into docs/ch folder also, and Treefrog-framework project README.ch, and INSTALL.ch. 
Maybe there still are some files or file content should be translated, please check it! Let me known if some files missed.

**Comment by treefrogframework** [comment]
Could you translate 'Cooperation with the Reverse Proxy Server' page?

So, Chinese pages are published.
http://treefrogframework.github.io/treefrog-framework/user-guide/ch/introduction/

**Comment by hks2002** [comment]
Yes, it already be translated. It seems this file is wrong when I export them from my CAT tools.
Besides, I find the format have been  changed. I need to review them. After that, I will create new PR.
Sorry for my mistake.

**Pull request merged**
