### PR TITLE
add escapeIdentifier column on update

### PR DESCRIPTION
**Pull request by mobilemindtec**
add escapeIdentifier column on update

### CODE REVIEW

**Comment by mobilemindtec** [comment]
add like upper on criteria condition - mysql ilike comparation

**Comment by treefrogframework** [comment]
I think that it's not proper to add TSql::LikeUpper, because upper() is a function.
You can use TSqlQuery class for complex SQL statement.

**Comment by mobilemindtec** [comment]
The ilike function present in criteria does not work in mysql. Using TSqlQuery I would lose the criteria benefit. I believe upper is the default way to simulate ilike in mysql.

**Comment by mobilemindtec** [comment]
In addition there is still the fix for the update in mysql, which does not use scape on column name.

**Comment by treefrogframework** [comment]
Patches to escape column  was committed in another pull-request.

**Pull request closed without merging**
