### PR TITLE
tviewhelper add jsTag()

### PR DESCRIPTION
**Pull request by hks2002**

### CODE REVIEW

**Comment by treefrogframework** [comment]
Please rename jsTag() to scriptTag().

Maybe,  attr.prepend("src", cssPath(src))  ->  attr.prepend("src", jsPath(src)) ?
Test it.

**Comment by hks2002** [comment]
changed the jsTag to scriptTag and cssPath to jsPath.
I have completed this test on my computer, it works ok! 
I only use the web to update this codes.cssPath is my input mistake,Sorry.

**Comment by treefrogframework** [comment]
I cannot merge it because including unnecessary commits.
Can you create a branch for this and send new pull-request?

**Comment by hks2002** [comment]
should I close this pull-request, and do a new pull-request again?or maybe should I open two pull-request? Because there is a templateName.split("/") changed to templateName.split(QDir::separator()) .

**Comment by hks2002** [comment]
New pull-request instead.

**Pull request closed without merging**
