### PR TITLE
parse application/xml or text/xml to formItems

### PR DESCRIPTION
**Pull request by stoneyrh**
Currently no way to access post xml data in http request.  This code just parse application/xml or text/xml into formItems with key "xml"
The xml will be decoded with encoding declared in charset, or UTF-8 by default

### CODE REVIEW

**Comment by aoym** [comment]
Could you create unit tests for this?
Dir:
 treeforg/src/test/

**Comment by stoneyrh** [comment]
I would like to, but I don't know how to do it yet

**Comment by aoym** [comment]
Refer thd dir "treefrog/src/test/*".

**Comment by aoym** [comment]
I think XML is old protocol now and not needed.

**Pull request closed without merging**
