### PR TITLE
Added named routes as an option

### PR DESCRIPTION
**Pull request by Akhilesh05**
I have added support for named routes as an option.
for example

> GET    /book                                         Book#all                  allBooks
> GET    /book/:param                             Book#show             showBook
> GET    /another/no/name/route             Controller#action

doing anywhere in the **controller** or **view**

`route("allBooks");`

will return "/book"
and doing

`route("showBook", {1});`

will return "/book/1"

### CODE REVIEW

**Comment by treefrogframework** [comment]
The name is needed?
I thought that
 route("Book#show", 1)
 returns "/book/1" was more simple.

And, the route() function is really useful?

**Comment by Akhilesh05** [comment]
I though of it in since I am a ruby on rails developer.
Rails have support for named routes. I found it useful so I implemented it in treefrog.

and since some routes might be like

> GET /book/:param/delete/:params Book#delete delete_book

then route("delete_route", {1, "just", "something"}) will return /book/1/delete/just/something

**Comment by treefrogframework** [comment]
> I though of it in since I am a ruby on rails developer.
> Rails have support for named routes. I found it useful so I implemented it in treefrog.

Noted.

Comments for your code:
- Add test cases for the program to src/test directory.
- Use QVector(), instead of std::vector().
- Add 'QUrl urln(const QString &name, const QStringList &args = QStringList(),
                 const QVariantMap &query = QVariantMap()) const' method into TActionHelper class, and test cases for this.

**Comment by treefrogframework** [comment]
The requests were not implemented.
Conflicts was not resolved.

**Pull request closed without merging**
